name: Android Build

on: pull_request

#jobs:
#  build:
#
#    runs-on: windows-latest
#
#    steps:
#      - uses: actions/checkout@v1
#
#      - name: Set up JDK
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#
#      - name: Run Tests
#        run: ./gredlew test
#
#      - name: Build Project
#        run: ./gradlew assemble
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install Danger
        run: yarn add danger danger-plugin-lint-report@1.0.0
      - name: Run Danger
        run: yarn danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}